
ALTER TABLE GIBOO.EMAIL_CERTIFICATION ADD CONSTRAINT FK_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES GIBOO."MEMBER"(MEMBER_NO) ON DELETE CASCADE;

-- DON
ALTER TABLE GIBOO.DONATION ADD CONSTRAINT FK_MEMBER_DON FOREIGN KEY (MEMBER_NO) REFERENCES GIBOO."MEMBER"(MEMBER_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.DONATION ADD CONSTRAINT FK_CATEGORY_DON FOREIGN KEY (CATEGORY_NO) REFERENCES GIBOO.CATEGORY(CATEGORY_NO) ON DELETE CASCADE;

--알람
ALTER TABLE GIBOO.ALARM ADD CONSTRAINT FK_ASK FOREIGN KEY (ASK_NO) REFERENCES GIBOO.ASK(ASK_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.ALARM ADD CONSTRAINT FK_CUSTOMER_SERVICE FOREIGN KEY (CS_NO) REFERENCES GIBOO.CUSTOMER_SERVICE(CS_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.ALARM ADD CONSTRAINT FK_DONATION FOREIGN KEY (DONATION_NO) REFERENCES GIBOO.DONATION(DONATION_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.ALARM ADD CONSTRAINT FK_EVENT FOREIGN KEY (EVENT_NO) REFERENCES GIBOO.EVENT(EVENT_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.ALARM ADD CONSTRAINT FK_MEMBER_ALARM FOREIGN KEY (MEMBER_NO) REFERENCES GIBOO."MEMBER"(MEMBER_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.ALARM ADD CONSTRAINT FK_NOTICE FOREIGN KEY (NOTICE_NO) REFERENCES GIBOO.NOTICE(NOTICE_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.ALARM ADD CONSTRAINT FK_PAYMENT FOREIGN KEY (PAYMENT_NO) REFERENCES GIBOO.PAYMENT(PAYMENT_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.ALARM ADD CONSTRAINT FK_RATE FOREIGN KEY (RATE_NO) REFERENCES GIBOO.RATE(RATE_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.ALARM ADD CONSTRAINT FK_RESERVES FOREIGN KEY (USAGE_NO) REFERENCES GIBOO.RESERVES(USAGE_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.ALARM ADD CONSTRAINT FK_REVIEW FOREIGN KEY (REVIEW_NO) REFERENCES GIBOO.REVIEW(REVIEW_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.ALARM ADD CONSTRAINT FK_VOLUNTEER FOREIGN KEY (VOLUNTEER_NO) REFERENCES GIBOO.VOLUNTEER(VOLUNTEER_NO) ON DELETE CASCADE;

--문의
ALTER TABLE GIBOO.ASK ADD CONSTRAINT FK_MEMBER_ASK FOREIGN KEY (MEMBER_NO) REFERENCES GIBOO."MEMBER"(MEMBER_NO) ON DELETE CASCADE;

--고객센터
ALTER TABLE GIBOO.CUSTOMER_SERVICE ADD CONSTRAINT FK_MANAGER_CUSTOMER_SERVICE FOREIGN KEY (MGR_NO) REFERENCES GIBOO.MANAGER(MGR_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.CUSTOMER_SERVICE ADD CONSTRAINT FK_MEMBER_CUSTOMER_SERVICE FOREIGN KEY (MEMBER_NO) REFERENCES GIBOO."MEMBER"(MEMBER_NO) ON DELETE CASCADE;

--이벤트
ALTER TABLE GIBOO.EVENT ADD CONSTRAINT FK_MANAGER_EVENT FOREIGN KEY (MGR_NO) REFERENCES GIBOO.MANAGER(MGR_NO) ON DELETE CASCADE;

-- 이벤트 참여
ALTER TABLE GIBOO.EVENT_REGISTER ADD CONSTRAINT FK_MEMBER_EVENT_REGISTER FOREIGN KEY (MEMBER_NO) REFERENCES GIBOO."MEMBER"(MEMBER_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.EVENT_REGISTER ADD CONSTRAINT FK_EVENT_EVENT_REGISTER FOREIGN KEY (EVENT_NO) REFERENCES GIBOO.EVENT(EVENT_NO) ON DELETE CASCADE;

-- 즐겨찾기
ALTER TABLE GIBOO.FAVORITES ADD CONSTRAINT FK_MEMBER_FAV FOREIGN KEY (MEMBER_NO) REFERENCES GIBOO."MEMBER"(MEMBER_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.FAVORITES ADD CONSTRAINT FK_DONATION_FAV FOREIGN KEY (DONATION_NO) REFERENCES GIBOO.DONATION(DONATION_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.FAVORITES ADD CONSTRAINT FK_VOLUNTEER_FAV FOREIGN KEY (VOLUNTEER_NO) REFERENCES GIBOO.VOLUNTEER(VOLUNTEER_NO) ON DELETE CASCADE;

--지도
ALTER TABLE GIBOO."MAP" ADD CONSTRAINT FK_DONATION_MAP FOREIGN KEY (DONATION_NO) REFERENCES GIBOO.DONATION(DONATION_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO."MAP" ADD CONSTRAINT FK_CATEGORY_MAP FOREIGN KEY (CATEGORY_NO) REFERENCES GIBOO.CATEGORY(CATEGORY_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO."MAP" ADD CONSTRAINT FK_VOLUNTEER_MAP FOREIGN KEY (VOLUNTEER_NO) REFERENCES GIBOO.VOLUNTEER(VOLUNTEER_NO) ON DELETE CASCADE;


--MYACTIVE
ALTER TABLE GIBOO.MYACTIVE ADD CONSTRAINT FK_DONATION_MYACT FOREIGN KEY (DONATION_NO) REFERENCES GIBOO.DONATION(DONATION_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.MYACTIVE ADD CONSTRAINT FK_VOLUNTEER_MYACT FOREIGN KEY (VOLUNTEER_NO) REFERENCES GIBOO.VOLUNTEER(VOLUNTEER_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.MYACTIVE ADD CONSTRAINT FK_MEMBER_MYACT FOREIGN KEY (MEMBER_NO) REFERENCES GIBOO."MEMBER"(MEMBER_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.MYACTIVE ADD CONSTRAINT FK_EVENT_MYACT FOREIGN KEY (EVENT_NO) REFERENCES GIBOO.EVENT(EVENT_NO) ON DELETE CASCADE;

--NOTICE
ALTER TABLE GIBOO.NOTICE ADD CONSTRAINT FK_MANAGER_NOTICE FOREIGN KEY (MGR_NO) REFERENCES GIBOO.MANAGER(MGR_NO) ON DELETE CASCADE;

-- PAY
ALTER TABLE GIBOO.PAYMENT ADD CONSTRAINT FK_MEMBER_PAY FOREIGN KEY (MEMBER_NO) REFERENCES GIBOO."MEMBER"(MEMBER_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.PAYMENT ADD CONSTRAINT FK_DONATION_PAY FOREIGN KEY (DONATION_NO) REFERENCES GIBOO.DONATION(DONATION_NO) ON DELETE CASCADE;

--RATE
ALTER TABLE GIBOO.RATE ADD CONSTRAINT FK_MEMBER_RATE FOREIGN KEY (MEMBER_NO) REFERENCES GIBOO."MEMBER"(MEMBER_NO) ON DELETE CASCADE;

--RESERVES
ALTER TABLE GIBOO.RESERVES ADD CONSTRAINT FK_MEMBER_RESERVES FOREIGN KEY (MEMBER_NO) REFERENCES GIBOO."MEMBER"(MEMBER_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.RESERVES ADD CONSTRAINT FK_DONATION_RESERVES FOREIGN KEY (DONATION_NO) REFERENCES GIBOO.DONATION(DONATION_NO) ON DELETE CASCADE;

--REVIEW
ALTER TABLE GIBOO.REVIEW ADD CONSTRAINT FK_MEMBER_REVIEW FOREIGN KEY (MEMBER_NO) REFERENCES GIBOO."MEMBER"(MEMBER_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.REVIEW ADD CONSTRAINT FK_DONATION_REVIEW FOREIGN KEY (DONATION_NO) REFERENCES GIBOO.DONATION(DONATION_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.REVIEW ADD CONSTRAINT FK_VOLUNTEER_REVIEW FOREIGN KEY (VOLUNTEER_NO) REFERENCES GIBOO.VOLUNTEER(VOLUNTEER_NO) ON DELETE CASCADE;

--VOL
ALTER TABLE GIBOO.VOLUNTEER ADD CONSTRAINT FK_MEMBER_VOL FOREIGN KEY (MEMBER_NO) REFERENCES GIBOO."MEMBER"(MEMBER_NO) ON DELETE CASCADE;
ALTER TABLE GIBOO.VOLUNTEER ADD CONSTRAINT FK_CATEGORY_VOL FOREIGN KEY (CATEGORY_NO) REFERENCES GIBOO.CATEGORY(CATEGORY_NO) ON DELETE CASCADE;








